# Generated by Django 3.2.4 on 2021-07-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrio',
            name='nombres',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='barrio',
            name='siglas',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='casa',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='casa',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=65),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellidos',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='cedula',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombres',
            field=models.CharField(max_length=50),
        ),
    ]
