# Generated by Django 3.2.4 on 2021-07-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0004_auto_20210711_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edificio',
            name='tipo',
            field=models.CharField(choices=[('residencial', 'Residencial'), ('rural', 'Rural')], max_length=30),
        ),
    ]
